scaffold_policy_name='effortless'
pkg_name='effortless'
pkg_origin="winhab"
pkg_version="0.0.1"
pkg_maintainer="Infrastructure Orchestration <infrastructureorchestration@aig.com>"
pkg_license="Apache-2.0"
pkg_description="Effortless package for all base cookbooks from Infra Orchestration"
pkg_upstream_url="http://chef.io"
pkg_scaffolding="chef/scaffolding-chef-infra"
